//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace graph.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("graph.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;graph&gt;
        ///  &lt;node id=&quot;23&quot;&gt;
        ///    &lt;link ref=&quot;21&quot; weight=&quot;4&quot; /&gt;
        ///    &lt;link ref=&quot;22&quot; weight=&quot;8&quot; /&gt;
        ///
        ///  &lt;/node&gt;
        ///  &lt;node id=&quot;12&quot;&gt;
        ///    &lt;link ref=&quot;11&quot; weight=&quot;5&quot; /&gt;
        ///    &lt;link ref=&quot;11&quot; weight=&quot;5&quot; /&gt; &lt;!--aa--&gt;
        ///    &lt;link ref=&quot;6&quot; weight=&quot;10&quot; /&gt;
        ///    &lt;link ref=&quot;20&quot; weight=&quot;5&quot; /&gt;
        ///  &lt;/node&gt;
        ///  &lt;node id=&quot;7&quot;&gt;
        ///    &lt;link ref=&quot;8&quot; weight=&quot;5&quot; /&gt;
        ///  &lt;/node&gt;
        ///  &lt;node id=&quot;10&quot;&gt;
        ///    &lt;link ref=&quot;9&quot; weight=&quot;4&quot; /&gt;
        ///    &lt;link ref=&quot;8&quot; weight=&quot;7&quot; /&gt;
        ///    &lt;link ref=&quot;11&quot; weight=&quot;7&quot; /&gt;
        ///  &lt;/node&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string doublelink {
            get {
                return ResourceManager.GetString("doublelink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt; 
        ///.
        /// </summary>
        internal static string doublenode {
            get {
                return ResourceManager.GetString("doublenode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt; 
        ///.
        /// </summary>
        internal static string linktoherself {
            get {
                return ResourceManager.GetString("linktoherself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;graph&gt;
        ///  &lt;node id=&quot;23&quot;&gt;
        ///    &lt;link ref=&quot;21&quot; weight=&quot;4&quot; /&gt;
        ///    &lt;link ref=&quot;22&quot; weight=&quot;8&quot; /&gt;
        ///
        ///  &lt;/node&gt;
        ///  &lt;node id=&quot;12&quot;&gt;
        ///    &lt;link ref=&quot;11&quot; weight=&quot;5&quot; /&gt;
        ///    &lt;link ref=&quot;6&quot; weight=&quot;10&quot; /&gt;
        ///    &lt;link ref=&quot;20&quot; weight=&quot;5&quot; /&gt;
        ///  &lt;/node&gt;
        ///  &lt;node id=&quot;7&quot;&gt;
        ///    &lt;link ref=&quot;8&quot; weight=&quot;5&quot; /&gt;
        ///  &lt;/node&gt;
        ///  &lt;node id=&quot;10&quot;&gt;
        ///    &lt;link ref=&quot;9&quot; weight=&quot;4&quot; /&gt;
        ///    &lt;link ref=&quot;8&quot; weight=&quot;7&quot; /&gt;
        ///    &lt;link ref=&quot;11&quot; weight=&quot;7&quot; /&gt;
        ///  &lt;/node&gt;
        /// 
        ///  &lt;node id=&quot;1&quot;&gt;
        ///    &lt;link ref=&quot;2&quot; weight=&quot;5&quot; /&gt;
        ///    &lt;link ref=&quot;3&quot; weight=&quot;7&quot; / [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string test1 {
            get {
                return ResourceManager.GetString("test1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;graph&gt;
        ///  &lt;node id=&quot;23&quot;&gt;
        ///    &lt;link ref=&quot;21&quot; weight=&quot;4&quot; /&gt;
        ///    &lt;link ref=&quot;22&quot; weight=&quot;8&quot; /&gt;
        ///
        ///  &lt;/node&gt;
        ///  &lt;node id=&quot;12&quot;&gt;
        ///    &lt;link ref=&quot;11&quot; weight=&quot;5&quot; /&gt;
        ///    &lt;link ref=&quot;6&quot; weight=&quot;10&quot; /&gt;
        ///    &lt;link ref=&quot;20&quot; weight=&quot;5&quot; /&gt;
        ///  &lt;/node&gt;
        ///  &lt;node id=&quot;7&quot;&gt;
        ///    &lt;link ref=&quot;8&quot; weight=&quot;5&quot; /&gt;
        ///  &lt;/node&gt;
        ///  &lt;node id=&quot;10&quot;&gt;
        ///    &lt;link ref=&quot;9&quot; weight=&quot;4&quot; /&gt;
        ///    &lt;link ref=&quot;8&quot; weight=&quot;7&quot; /&gt;
        ///    &lt;link ref=&quot;11&quot; weight=&quot;7&quot; /&gt;
        ///  &lt;/node&gt;
        /// 
        ///  &lt;node id=&quot;1&quot;&gt;
        ///    &lt;link ref=&quot;2&quot; weight=&quot;5&quot; /&gt;
        ///    &lt;link ref=&quot;3&quot; weight=&quot;7&quot; / [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string test11 {
            get {
                return ResourceManager.GetString("test11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;graph&gt;
        ///  &lt;node id=&quot;1&quot;&gt;
        ///    &lt;link ref=&quot;2&quot; weight=&quot;4&quot; /&gt;
        ///    &lt;link ref=&quot;3&quot; weight=&quot;5&quot; /&gt;
        ///    &lt;link ref=&quot;4&quot; weight=&quot;6&quot; /&gt;
        ///    &lt;link ref=&quot;5&quot; weight=&quot;7&quot; /&gt;
        ///  &lt;/node&gt;
        ///  &lt;node id=&quot;2&quot;&gt;
        ///    &lt;link ref=&quot;1&quot; weight=&quot;4&quot; /&gt;
        ///    &lt;link ref=&quot;6&quot; weight=&quot;4&quot; /&gt;
        ///  &lt;/node&gt;
        ///  &lt;node id=&quot;3&quot;&gt;
        ///    &lt;link ref=&quot;1&quot; weight=&quot;5&quot; /&gt;
        ///    &lt;link ref=&quot;6&quot; weight=&quot;5&quot; /&gt;
        ///  &lt;/node&gt;
        ///  &lt;node id=&quot;4&quot;&gt;
        ///    &lt;link ref=&quot;1&quot; weight=&quot;6&quot; /&gt;
        ///    &lt;link ref=&quot;6&quot; weight=&quot;6&quot; /&gt;
        ///  &lt;/node&gt;
        ///  &lt;node id=&quot;5&quot;&gt;
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string test2 {
            get {
                return ResourceManager.GetString("test2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;graph&gt;
        ///  &lt;node id=&quot;1&quot;&gt;
        ///    &lt;link ref=&quot;2&quot; weight=&quot;11&quot; /&gt;
        ///    &lt;link ref=&quot;5&quot; weight=&quot;10&quot; /&gt;
        ///
        ///  &lt;/node&gt;
        ///  &lt;node id=&quot;2&quot;&gt;
        ///    &lt;link ref=&quot;1&quot; weight=&quot;11&quot; /&gt;
        ///    &lt;link ref=&quot;6&quot; weight=&quot;4&quot; /&gt;
        ///    &lt;link ref=&quot;3&quot; weight=&quot;1&quot; /&gt;
        ///  &lt;/node&gt;
        ///  &lt;node id=&quot;3&quot;&gt;
        ///    &lt;link ref=&quot;2&quot; weight=&quot;1&quot; /&gt;
        ///    &lt;link ref=&quot;6&quot; weight=&quot;3&quot; /&gt;
        ///    &lt;link ref=&quot;4&quot; weight=&quot;1&quot; /&gt;
        ///  &lt;/node&gt;
        ///  &lt;node id=&quot;4&quot;&gt;
        ///    &lt;link ref=&quot;3&quot; weight=&quot;1&quot; /&gt;
        ///    &lt;link ref=&quot;6&quot; weight=&quot;1&quot; /&gt;
        ///    &lt;link ref=&quot;5&quot; weight=&quot;2&quot; /&gt;
        ///  &lt;/node&gt;
        /// 
        ///  &lt;node id=&quot;5&quot;&gt;
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string test3 {
            get {
                return ResourceManager.GetString("test3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt; 
        ///.
        /// </summary>
        internal static string twingraph {
            get {
                return ResourceManager.GetString("twingraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt; 
        ///.
        /// </summary>
        internal static string zerolink {
            get {
                return ResourceManager.GetString("zerolink", resourceCulture);
            }
        }
    }
}
